
  ## K Nearest Neighbors Exercise

Import pandas and numpy packages

In [2]:
import numpy as np
import pandas as pd

Read the iris CSV file

In [3]:
data = pd.read_csv('iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

Explore the data

In [4]:
print(data.describe().T)

              count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.054000  0.433594  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758667  1.764420  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.198667  0.763161  0.1  0.3  1.30  1.8  2.5
species       150.0  1.000000  0.819232  0.0  0.0  1.00  2.0  2.0


Create two variables for features and target.  Convert them into values.

In [25]:
features = data[['sepal_length','sepal_width', 'petal_length', 'petal_width']].values
target = data.species.values

Scikit-learn has a function to split data into training and testing sets

In [11]:
from sklearn.model_selection import train_test_split

Apply train_test_split to sample data

In [9]:
conditions = [['M',67],['Tu',74],['W',80],['Th',68],['F',78]]
sales = [240,360,700,320,1100]

In [12]:
f_train, f_test, t_train, t_test = train_test_split(
        conditions, sales, test_size=0.20)

View results of train_test_split 

In [13]:
print('Training Set')
print(f_train)
print(t_train,'\n\n')
print('Test Set')
print(f_test)
print(t_test)

Training Set
[['W', 80], ['F', 78], ['Th', 68], ['M', 67]]
[700, 1100, 320, 240] 


Test Set
[['Tu', 74]]
[360]


Split the iris data into training set and test set

In [26]:
features_train, features_test, target_train, target_test = train_test_split(
        features, target, test_size=0.20)

In [27]:
print(features_train.shape)
print(target_train.shape)

print(features_test.shape)
print(target_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


Import the K Nearest Neighbors classifier from scikit-learn

In [28]:
from sklearn.neighbors import KNeighborsClassifier

Train the KNN classifier

In [29]:
iris_model = KNeighborsClassifier(5).fit(features_train, target_train)

Compare predictions with actual results

In [31]:
print(iris_model.predict(features_test))

[2 1 2 2 0 2 1 2 0 1 0 0 0 1 2 2 1 2 2 0 2 1 1 2 0 0 1 0 2 2]


Predict probabilities

In [32]:
print(target_test)

[2 1 2 2 0 2 1 2 0 1 0 0 0 1 2 2 1 2 1 0 2 1 1 2 0 0 1 0 2 2]


Score the model

In [35]:
iris_model.predict_proba(features_test)

array([[0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.2, 0.8],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ]])

## K-Folds Cross-Validation

Remember how to index numpy arrays with indices?

In [38]:
conditions = np.array([['M',67],['Tu',74],['W',80],['Th',68],['F',78]])
sales = np.array([240,360,700,320,1100])
indices = [4,0,2]

In [42]:
pd.DataFrame(zip(conditions[indices], sales[indices]))

0     1
0  [F, 78]  1100
1  [M, 67]   240
2  [W, 80]   700

Import the KFold function from scikit-learn

In [43]:
from sklearn.model_selection import KFold

KFold function creates indices for separating training and test sets

In [44]:
k_fold_indices = KFold(5, shuffle=True)
print(k_fold_indices)

KFold(n_splits=5, random_state=None, shuffle=True)


Let's see what is in the k_fold_indices

In [46]:
for train_indices,test_indices in k_fold_indices.split(conditions):
    print(train_indices, test_indices)

[0 1 3 4] [2]
[0 2 3 4] [1]
[0 1 2 3] [4]
[1 2 3 4] [0]
[0 1 2 4] [3]


Let's use the indices to index values in an array.

In [47]:
for train_indices,test_indices in k_fold_indices.split(conditions,sales):
    print('Training Set')
    print(conditions[train_indices])
    print(sales[train_indices])
    print('Test Set')
    print(conditions[test_indices])
    print(sales[test_indices]) 
    print()

Training Set
[['M' '67']
 ['Tu' '74']
 ['Th' '68']
 ['F' '78']]
[ 240  360  320 1100]
Test Set
[['W' '80']]
[700]

Training Set
[['M' '67']
 ['Tu' '74']
 ['W' '80']
 ['Th' '68']]
[240 360 700 320]
Test Set
[['F' '78']]
[1100]

Training Set
[['M' '67']
 ['Tu' '74']
 ['W' '80']
 ['F' '78']]
[ 240  360  700 1100]
Test Set
[['Th' '68']]
[320]

Training Set
[['M' '67']
 ['W' '80']
 ['Th' '68']
 ['F' '78']]
[ 240  700  320 1100]
Test Set
[['Tu' '74']]
[360]

Training Set
[['Tu' '74']
 ['W' '80']
 ['Th' '68']
 ['F' '78']]
[ 360  700  320 1100]
Test Set
[['M' '67']]
[240]



Function for calculating cross-validation

In [48]:
from sklearn.model_selection import cross_val_score

In [49]:
# cross validation function with average score
def cross_validate(features, target, classifier, k_fold=10, r_state=None) :
    k_fold_indices = KFold(k_fold,shuffle=True, random_state=r_state)
    scores = cross_val_score(classifier, features, target, cv=k_fold_indices)
    return scores.mean()

Test the cross_validate function with different numbers of neighbors

In [51]:

print(cross_validate(features,target,KNeighborsClassifier(3),10,0))

0.96


## Exercise
#### 1. Load the clean_data.csv as a DataFrame

In [52]:
exe_data = pd.read_csv('clean_data.csv')

#### 2. Separate the data into features (age_all, is_female, pclass, embarked dummy variables, fare) and target (Note: Make sure you convert the data to a numpy array by typing .values at end of DataFrame)

In [76]:
exe_data_features = exe_data[['Age_all','Is_female','Pclass','Embarked_C','Embarked_Q','Embarked_S', 'Fare']].values
exe_data_target = exe_data.Survived.values

#### 3. Build a KNN model and test the accuracy of the model using kfold cross-validation

In [77]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier

def cross_validate(features,target,classifier,k_fold=10,r_state=None):
    k_fold_indices=KFold(k_fold,shuffle=True,random_state=r_state)
    scores=cross_val_score(classifier,features,target,cv=k_fold_indices)
    return scores.mean()


print(cross_validate(exe_data_features,exe_data_target,KNeighborsClassifier(n_neighbors=3, weights = 'distance'),10,0))

0.709350811485643


#### 4. Try different numbers of neighbors and vary weights (uniform and distance) using a for loop

In [78]:
#fold = [[5,10]]

for f in range (5,10):
     print(cross_validate(exe_data_features,exe_data_target,KNeighborsClassifier(n_neighbors=3,weights = 'distance'),10,0))   

0.709350811485643
0.709350811485643
0.709350811485643
0.709350811485643
0.709350811485643


In [79]:
for k in range (1,101):
    print(cross_validate(exe_data_features,exe_data_target,KNeighborsClassifier(k, weights = 'distance'),10,0),
         cross_validate(exe_data_features,exe_data_target,KNeighborsClassifier(k, weights = 'uniform'),10,0))

0.6779275905118602 0.6779275905118602
0.6846566791510612 0.6700998751560548
0.709350811485643 0.7003995006242196
0.7015106117353309 0.6891760299625469
0.7104868913857677 0.6857677902621722
0.7082147315855181 0.6913607990012485
0.7138451935081148 0.7059300873907616
0.7272534332084893 0.7014357053682896
0.7283895131086141 0.7205118601747815
0.7261298377028714 0.7093133583021224
0.7227715355805244 0.7126591760299626
0.7227590511860176 0.7149063670411986
0.7182771535580524 0.7160049937578028
0.7272659176029963 0.7160424469413234
0.7216354556803996 0.7171285892634207
0.7227840199750313 0.7092883895131086
0.7160424469413234 0.7025468164794008
0.7250312109862672 0.7137952559300873
0.7261423220973782 0.7171285892634207
0.7216479400749063 0.7171535580524344
0.7238701622971286 0.7137702871410736
0.7261173533083645 0.7081647940074907
0.7283520599250937 0.7103995006242196
0.7261298377028714 0.7126466916354557
0.7317103620474408 0.7070287141073659
0.7328339575530587 0.7025717852684146
0.73620474406

### Bonus: Create a DataFrame with columns for different values of k neighbors and the corresponding scores for both uniform and distance weighted models.  Determine which model has the best performance

In [80]:
results = pd.DataFrame(columns = 'k_values', 'd_accuracy', 'u_accuracy')

SyntaxError: positional argument follows keyword argument (<ipython-input-80-55d728205f18>, line 1)

## Data Normalization

Calculate the mean and standard deviation

In [81]:
avg_age = exe_data.Age_all.mean()
stdev_age = exe_data.Age_all.std()

In [82]:
exe_data[exe_data['Age'] != exe_data['Age_all']].head()

PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6         0       3               Moran, Mr. James    male  NaN   
17           18         1       2   Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3        Masselmani, Mrs. Fatima  female  NaN   
26           27         0       3        Emir, Mr. Farred Chehab    male  NaN   
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare  ... Embarked Is_female  Embarked_C  \
5       0      0  330877   8.4583  ...        Q     False           0   
17      0      0  244373  13.0000  ...        S     False           0   
19      0      0    2649   7.2250  ...        C      True           1   
26      0      0    2631   7.2250  ...        C     False           1   
28      0      0  330959   7.8792  ...        Q      True           0   

    Embarked_Q  Embarked_S  Title    Age_all    Age_sex  Age_norm  Fare_norm  
5            1           0     Mr  29.699118  30.726645       0.0  -0.477848  
17           0           1     Mr  29.699118  30.726645       0.0  -0.386454  
19           0           0    Mrs  29.699118  27.915709       0.0  -0.502666  
26           0           0     Mr  29.699118  30.726645       0.0  -0.502666  
28           1           0   Miss  29.699118  27.915709       0.0  -0.489502  

[5 rows x 21 columns]

In [83]:
avg_fare = exe_data.Fare.mean()
stdv_fare = exe_data.Fare.std()

Subtract the mean and divide by the standard deviation

In [84]:
exe_data['Age_norm'] = (exe_data.Age_all - avg_age)/stdev_age
exe_data['Fare_norm'] = (exe_data.Fare - avg_fare)/stdv_fare


Create new features using normalized data

In [85]:
features_norm = exe_data[['Age_norm', 'Is_female', 'Pclass', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Fare_norm']].values

Test KNN on normalized data

In [86]:
for k in range (1,101):
    print(cross_validate(exe_data_features,exe_data_target,KNeighborsClassifier(k, weights = 'distance'),10,0),
         cross_validate(features_norm,exe_data_target,KNeighborsClassifier(k, weights = 'distance'),10,0))

0.6779275905118602 0.7677153558052434
0.6846566791510612 0.7800624219725343
0.709350811485643 0.8024968789013732
0.7015106117353309 0.8013732833957554
0.7104868913857677 0.8047440699126092
0.7082147315855181 0.8024843945068664
0.7138451935081148 0.8125967540574284
0.7272534332084893 0.8024843945068664
0.7283895131086141 0.8058551810237203
0.7261298377028714 0.8036079900124845
0.7227715355805244 0.8058551810237203
0.7227590511860176 0.8013483146067417
0.7182771535580524 0.8024843945068664
0.7272659176029963 0.8024719101123596
0.7216354556803996 0.8013483146067415
0.7227840199750313 0.8013483146067417
0.7160424469413234 0.7991011235955057
0.7250312109862672 0.7968539325842697
0.7261423220973782 0.8002247191011236
0.7216479400749063 0.7991136079900125
0.7238701622971286 0.7979900124843946
0.7261173533083645 0.7991136079900125
0.7283520599250937 0.8013607990012483
0.7261298377028714 0.7991136079900125
0.7317103620474408 0.8013607990012485
0.7328339575530587 0.8013607990012485
0.73620474406

## Random Forest

Import the Random Forest function

In [87]:
from sklearn.ensemble import RandomForestClassifier

Create an instance of a random forest classifier.  Random state is used to set random number generator for reproducible results

In [88]:
model = RandomForestClassifier(30, random_state = 2)

Run the cross-validation function using the Random Forest algorithm

In [89]:
cross_validate(features_norm,exe_data_target,model,10,0)

0.8080898876404493

Investigate feature importances

In [90]:
model.fit(features_norm, exe_data_target).feature_importances_

array([0.28853271, 0.27865361, 0.09638645, 0.01081777, 0.008052  ,
       0.01388902, 0.30366844])

### Make a Prediction for Kaggle

Train the model using the best data available (in the case of the Titanic you'll use all the data)

In [91]:
model=RandomForestClassifier(30,random_state=None).fit(features_norm,exe_data_target)

Create a DataFrame with the test.csv data

In [92]:
test_data	=	pd.read_csv('test.csv')	
test_data.info()	
print(test_data.head())	
print(test_data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myl

Clean text and missing age values

In [93]:
test_data['Is_female']	=	test_data.Sex.replace(['female','male'],[True,False])
test_data['Age_all']	=	test_data.Age.fillna(avg_age)

Convert Embarked to dummies and merge to data

In [94]:
embarked	=	pd.get_dummies(test_data.Embarked,		
																																															prefix	=	'Embarked')	
test_data	=	pd.merge(test_data,	embarked,		
																																left_index=True,	right_index=True)

Clean missing fare values

In [95]:
test_data.Fare.fillna(avg_fare,inplace=True)

Select features from test data and convert to numpy array

In [96]:
test_features	=	test_data[['Age_all',	'Is_female',		
													'Pclass',	'Embarked_C',	'Embarked_Q',		
													'Embarked_S',	'Fare']].values

Create predictions

In [97]:
predictions	=		model.predict(test_features)

Add Predictions as new column in DataFrame

In [98]:
test_data['Survived']	=	predictions

Save as CSV (make sure you set index=False)

In [99]:
kaggle	=	test_data[['PassengerId','Survived']]	
kaggle.to_csv('kaggle_titanic_submission.csv',		
																										index=False)